application: elegant-tangent-99223
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: note_site.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest